[package]
name = "inlier"
version = "0.1.0"
edition = "2024"

[features]
default = ["rayon"]
rayon = ["argmin/rayon"]

[dependencies]
argmin = "0.11.0"
nalgebra = { version = "0.33", features = ["std"] }
ordered-float = "5.1.0"
rand = "0.8"
usearch = "2.21.4"
float-ord = "0.3.2"
kornia-pnp = "0.1.10"

[dev-dependencies]
plotters = "0.3"
